#!/bin/env python


import sys, os
if len(sys.argv) < 2:
	print "Error - unspecified project name"
	exit()
	
cwd = os.getcwd()

template = "[Desktop Entry]\n\
Comment[en_US]=GVim Loader\n\
Comment=GVim loader\n\
Exec=gvim -c 'cd "+cwd+"'\n\
GenericName[en_US]=\n\
GenericName=\n\
Icon=/home/charlie/library/images/icons/gvim2.png\n\
MimeType=\n\
Name[en_US]="+sys.argv[1]+" - GVim\n\
Name="+sys.argv[1]+" - GVim\n\
Path=\n\
StartupNotify=true\n\
Terminal=false\n\
TerminalOptions=\n\
Type=Application\n\
X-DBUS-ServiceName=\n\
X-DBUS-StartupType=\n\
X-KDE-SubstituteUID=false\n\
X-KDE-Username="


ft = open("/home/charlie/development/quick/"+sys.argv[1], "w")
ft.write(template)
ft.close()